/**
 * 技能五子棋 v8
 * 修复：完整棋盘线条、棋子对比度、读秒3次机会、按钮交互
 */
var CONFIG={BOARD_SIZE:19,CELL_SIZE:0,PIECE_RADIUS:0,AI_DELAY:800};
var LAYOUT={topH:40,chatH:90,actionH:100,boardLeft:0,boardTop:0,boardPx:0};
var gameState='menu',currentScreen='';
var board=[],currentPlayer=1,isMyTurn=true;
var gameOver=false,winner=null,lastMove=null;
var previewX=-1,previewY=-1,canPlace=false;
var playerTime=15,aiTime=15,timerInterval=null;
var playerTimeoutCount=0,aiTimeoutCount=0;
var chatMessages=[],currentTime='00:00';
var menuButtons=[];
var hoveredBtn=null;
var settings={normalMode:{difficulty:'normal',countdown:false,playerColor:0},general:{sound:true,music:true,vibration:true}};
var systemInfo,canvas,ctx,W,H;
function init(){try{systemInfo=tt.getSystemInfoSync();W=systemInfo.windowWidth;H=systemInfo.windowHeight;canvas=tt.createCanvas();canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');var boardPx=W-20;CONFIG.CELL_SIZE=boardPx/(CONFIG.BOARD_SIZE-1);CONFIG.PIECE_RADIUS=CONFIG.CELL_SIZE*0.44;LAYOUT.boardPx=boardPx;LAYOUT.boardLeft=10;LAYOUT.boardTop=LAYOUT.topH+50;initMenu();tt.onTouchStart(handleTouch);tt.onTouchMove(handleTouchMove);tt.onTouchEnd(handleTouchEnd);updateTime();setInterval(updateTime,1000);gameLoop();}catch(e){console.error('Init error:',e);}}
function updateTime(){var d=new Date();currentTime=pad2(d.getHours())+':'+pad2(d.getMinutes());}
function pad2(n){return n<10?'0'+n:''+n;}
function initMenu(){currentScreen='main_menu';menuButtons=[];var btnW=Math.min(W*0.7,280),btnH=50,cx=W/2;var startY=H*0.32,gap=65;menuButtons.push({id:'mode_normal',text:'传统五子棋',x:cx,y:startY,w:btnW,h:btnH});menuButtons.push({id:'mode_skill',text:'技能五子棋',x:cx,y:startY+gap,w:btnW,h:btnH});menuButtons.push({id:'mode_multi',text:'多人五子棋',x:cx,y:startY+gap*2,w:btnW,h:btnH});menuButtons.push({id:'settings',text:'设置',x:cx,y:startY+gap*3,w:btnW,h:btnH});}
function initSettings(){currentScreen='settings';menuButtons=[];var cx=W/2,startY=H*0.28;var set=settings.general;menuButtons.push({id:'lbl_sound',text:'音效',x:30,y:startY,type:'label'});menuButtons.push({id:'sound_on',text:'开启',x:cx-65,y:startY+35,w:120,h:36,type:'toggle',isOn:set.sound});menuButtons.push({id:'sound_off',text:'关闭',x:cx+65,y:startY+35,w:120,h:36,type:'toggle',isOn:!set.sound});menuButtons.push({id:'lbl_music',text:'音乐',x:30,y:startY+100,type:'label'});menuButtons.push({id:'music_on',text:'开启',x:cx-65,y:startY+135,w:120,h:36,type:'toggle',isOn:set.music});menuButtons.push({id:'music_off',text:'关闭',x:cx+65,y:startY+135,w:120,h:36,type:'toggle',isOn:!set.music});menuButtons.push({id:'lbl_vibe',text:'震动反馈',x:30,y:startY+200,type:'label'});menuButtons.push({id:'vibe_on',text:'开启',x:cx-65,y:startY+235,w:120,h:36,type:'toggle',isOn:set.vibration});menuButtons.push({id:'vibe_off',text:'关闭',x:cx+65,y:startY+235,w:120,h:36,type:'toggle',isOn:!set.vibration});menuButtons.push({id:'back',text:'返回',x:cx,y:H-60,w:120,h:40,type:'btn'});}
function initCreateGame(){currentScreen='create_game';menuButtons=[];var cx=W/2,startY=H*0.25;var s=settings.normalMode;menuButtons.push({id:'lbl_diff',text:'人机难度',x:30,y:startY,type:'label'});var dw=70,dg=8,dy=startY+35;var ds=['easy','normal','hard','extreme'],dl=['简单','普通','困难','极限'];var dx=cx-(dw*4+dg*3)/2;for(var i=0;i<4;i++)menuButtons.push({id:'diff_'+ds[i],text:dl[i],x:dx+dw/2+i*(dw+dg),y:dy,w:dw,h:34,type:'diff',diff:ds[i]});menuButtons.push({id:'lbl_color',text:'执子',x:30,y:startY+100,type:'label'});menuButtons.push({id:'color_guess',text:'猜先',x:cx-80,y:startY+135,w:100,h:36,type:'color',color:0});menuButtons.push({id:'color_black',text:'执黑',x:cx,y:startY+135,w:100,h:36,type:'color',color:1});menuButtons.push({id:'color_white',text:'执白',x:cx+80,y:startY+135,w:100,h:36,type:'color',color:2});menuButtons.push({id:'lbl_timer',text:'是否读秒',x:30,y:startY+200,type:'label'});menuButtons.push({id:'timer_on',text:'开启',x:cx-65,y:startY+235,w:120,h:36,type:'toggle',isOn:s.countdown});menuButtons.push({id:'timer_off',text:'关闭',x:cx+65,y:startY+235,w:120,h:36,type:'toggle',isOn:!s.countdown});menuButtons.push({id:'start_game',text:'进入游戏',x:cx,y:H-100,w:160,h:50,type:'btn_large'});menuButtons.push({id:'back',text:'返回',x:cx,y:H-40,w:120,h:35,type:'btn'});}
function handleTouch(e){var touch=e.touches?e.touches[0]:e;var x=touch.clientX,y=touch.clientY;if(gameState==='menu')handleMenuTouch(x,y);else if(gameState==='game')handleGameTouch(x,y);}
function handleTouchMove(e){var touch=e.touches?e.touches[0]:e;var x=touch.clientX,y=touch.clientY;hoveredBtn=getHoveredBtn(x,y);if(gameState==='game')handleGameHover(x,y);}
function handleTouchEnd(e){hoveredBtn=null;}
function getHoveredBtn(x,y){for(var i=0;i<menuButtons.length;i++){var b=menuButtons[i];if(!b.w||!b.h)continue;if(x>=b.x-b.w/2&&x<=b.x+b.w/2&&y>=b.y-b.h/2&&y<=b.y+b.h/2)return b;}return null;}
function handleMenuTouch(x,y){for(var i=0;i<menuButtons.length;i++){var b=menuButtons[i];if(!b.w)continue;if(x>=b.x-b.w/2&&x<=b.x+b.w/2&&y>=b.y-b.h/2&&y<=b.y+b.h/2){onMenuBtn(b.id,b);break;}}}
function onMenuBtn(id,btn){var s=settings.normalMode,g=settings.general;if(id==='mode_normal'){initCreateGame();}else if(id==='mode_skill'||id==='mode_multi'){}else if(id==='settings'){initSettings();}else if(id==='back'){if(currentScreen==='create_game'||currentScreen==='settings')initMenu();else initMenu();}else if(id==='start_game'){gameState='game';initGame();}else if(btn.type==='diff'){s.difficulty=btn.diff;initCreateGame();}else if(btn.type==='color'){s.playerColor=btn.color;initCreateGame();}else if(id==='timer_on'){s.countdown=true;initCreateGame();}else if(id==='timer_off'){s.countdown=false;initCreateGame();}else if(id==='sound_on'){g.sound=true;initSettings();}else if(id==='sound_off'){g.sound=false;initSettings();}else if(id==='music_on'){g.music=true;initSettings();}else if(id==='music_off'){g.music=false;initSettings();}else if(id==='vibe_on'){g.vibration=true;initSettings();}else if(id==='vibe_off'){g.vibration=false;initSettings();}}
function handleGameHover(x,y){var chatY=H-LAYOUT.chatH;var actionY=chatY-LAYOUT.actionH;hoveredBtn=null;if(y>=actionY&&y<chatY){var cx=W/2;var confirmX=cx-80,confirmY=actionY+10,confirmW=160,confirmH=50;if(x>=confirmX&&x<=confirmX+confirmW&&y>=confirmY&&y<=confirmY+confirmH){hoveredBtn={id:'confirm'};return;}var btnW=80,btnH=36,btnGap=12;var totalW=btnW*3+btnGap*2;var startX=cx-totalW/2;var btnY=actionY+60;for(var i=0;i<3;i++){var bx=startX+i*(btnW+btnGap);if(x>=bx&&x<=bx+btnW&&y>=btnY&&y<=btnY+btnH){hoveredBtn={id:['resign','undo','draw'][i]};return;}}}}}
function handleGameTouch(x,y){var chatY=H-LAYOUT.chatH;var actionY=chatY-LAYOUT.actionH;if(y>=chatY)return;if(y>=actionY){handleActionTouch(x,y,actionY);return;}if(gameOver){var btnY=H*0.55;if(x>=W/2-70&&x<=W/2+70&&y>=btnY&&y<=btnY+45){initGame();return;}if(x>=W/2-50&&x<=W/2+50&&y>=btnY+55&&y<=btnY+95){backToMenu();}return;}var myColor=settings.normalMode.playerColor;if(currentPlayer!==myColor)return;var bL=LAYOUT.boardLeft,bT=LAYOUT.boardTop;var bx=x-bL,by=y-bT;var bs=CONFIG.CELL_SIZE*(CONFIG.BOARD_SIZE-1);if(bx<-CONFIG.PIECE_RADIUS||by<-CONFIG.PIECE_RADIUS||bx>bs+CONFIG.PIECE_RADIUS||by>bs+CONFIG.PIECE_RADIUS)return;var gx=Math.round(bx/CONFIG.CELL_SIZE);var gy=Math.round(by/CONFIG.CELL_SIZE);if(gx<0||gx>=CONFIG.BOARD_SIZE||gy<0||gy>=CONFIG.BOARD_SIZE)return;if(board[gy][gx]!==0)return;previewX=gx;previewY=gy;canPlace=true;}
function handleActionTouch(x,y,actionY){var cx=W/2;var confirmX=cx-80,confirmY=actionY+10,confirmW=160,confirmH=50;if(x>=confirmX&&x<=confirmX+confirmW&&y>=confirmY&&y<=confirmY+confirmH){if(canPlace)confirmPlace();return;}var btnW=80,btnH=36,btnGap=12;var totalW=btnW*3+btnGap*2;var startX=cx-totalW/2;var btnY=actionY+60;for(var i=0;i<3;i++){var bx=startX+i*(btnW+btnGap);if(x>=bx&&x<=bx+btnW&&y>=btnY&&y<=btnY+btnH){if(i===0)onResign();else if(i===1)onUndo();else if(i===2)onDraw();return;}}}
function onResign(){endGame(settings.normalMode.playerColor===1?2:1);}
function onDraw(){}
function onUndo(){if(!lastMove)return;board[lastMove.y][lastMove.x]=0;lastMove=null;previewX=-1;previewY=-1;canPlace=false;currentPlayer=settings.normalMode.playerColor;isMyTurn=true;}
function confirmPlace(){if(!canPlace||previewX<0||previewY<0)return;var myColor=settings.normalMode.playerColor;placePiece(previewX,previewY,myColor);previewX=-1;previewY=-1;canPlace=false;if(checkWin(lastMove.x,lastMove.y,myColor)){endGame(myColor);return;}currentPlayer=myColor===1?2:1;isMyTurn=false;playerTime=settings.normalMode.countdown?15:9999;aiTime=settings.normalMode.countdown?15:9999;setTimeout(aiMove,CONFIG.AI_DELAY);}
function initGame(){board=[];for(var y=0;y<CONFIG.BOARD_SIZE;y++){board[y]=[];for(var x=0;x<CONFIG.BOARD_SIZE;x++)board[y][x]=0;}if(settings.normalMode.playerColor===0)settings.normalMode.playerColor=Math.random()<0.5?1:2;currentPlayer=1;var myColor=settings.normalMode.playerColor;isMyTurn=(myColor===1);gameOver=false;winner=null;lastMove=null;previewX=-1;previewY=-1;canPlace=false;playerTime=settings.normalMode.countdown?15:9999;aiTime=settings.normalMode.countdown?15:9999;playerTimeoutCount=0;aiTimeoutCount=0;chatMessages=[];if(timerInterval)clearInterval(timerInterval);if(settings.normalMode.countdown){timerInterval=setInterval(function(){if(gameOver){clearInterval(timerInterval);return;}if(isMyTurn){playerTime--;if(playerTime<=0){playerTime=15;playerTimeoutCount++;if(playerTimeoutCount>=3){endGame(myColor===1?2:1);}else{onTimeoutSkip();}}}else{aiTime--;if(aiTime<=0){aiTime=15;aiTimeoutCount++;if(aiTimeoutCount>=3){endGame(myColor);}else{aiMove();}}}},1000);}if(!isMyTurn)setTimeout(aiMove,CONFIG.AI_DELAY);}
function onTimeoutSkip(){currentPlayer=settings.normalMode.playerColor===1?2:1;isMyTurn=false;playerTime=settings.normalMode.countdown?15:9999;aiTime=settings.normalMode.countdown?15:9999;chatMessages.push('你停了一手('+playerTimeoutCount+'/3)');setTimeout(aiMove,CONFIG.AI_DELAY);}
function placePiece(x,y,player){board[y][x]=player;lastMove={x:x,y:y};}
function checkWin(x,y,player){var dirs=[[1,0],[0,1],[1,1],[1,-1]];for(var d=0;d<dirs.length;d++){var count=1;for(var i=1;i<5;i++){var nx=x+dirs[d][0]*i,ny=y+dirs[d][1]*i;if(nx<0||nx>=CONFIG.BOARD_SIZE||ny<0||ny>=CONFIG.BOARD_SIZE||board[ny][nx]!==player)break;count++;}for(var i=1;i<5;i++){var nx=x-dirs[d][0]*i,ny=y-dirs[d][1]*i;if(nx<0||nx>=CONFIG.BOARD_SIZE||ny<0||ny>=CONFIG.BOARD_SIZE||board[ny][nx]!==player)break;count++;}if(count>=5)return true;}return false;}
function endGame(w){gameOver=true;winner=w;if(timerInterval)clearInterval(timerInterval);}
function backToMenu(){if(timerInterval)clearInterval(timerInterval);gameState='menu';currentScreen='';previewX=-1;previewY=-1;canPlace=false;hoveredBtn=null;initMenu();}
function aiMove(){if(gameOver)return;var myColor=settings.normalMode.playerColor;var aiColor=myColor===1?2:1;var move=findBestMove(aiColor);if(move){placePiece(move.x,move.y,aiColor);if(checkWin(move.x,move.y,aiColor)){endGame(aiColor);return;}currentPlayer=myColor;isMyTurn=true;playerTime=settings.normalMode.countdown?15:9999;aiTime=settings.normalMode.countdown?15:9999;}}
function findBestMove(aiColor){var maxScore=-1,candidates=[];for(var y=0;y<CONFIG.BOARD_SIZE;y++){for(var x=0;x<CONFIG.BOARD_SIZE;x++){if(board[y][x]===0){var score=evalPoint(x,y,aiColor);if(score>maxScore){maxScore=score;candidates=[{x:x,y:y}];}else if(score===maxScore)candidates.push({x:x,y:y});}}}if(!candidates.length){var c=Math.floor(CONFIG.BOARD_SIZE/2);return{x:c,y:c};}return candidates[Math.floor(Math.random()*candidates.length)];}
function evalPoint(x,y,aiColor){var score=0,dirs=[[1,0],[0,1],[1,1],[1,-1]];var playerColor=settings.normalMode.playerColor;for(var d=0;d<dirs.length;d++){score+=evalLine(x,y,dirs[d][0],dirs[d][1],aiColor)*1.2;score+=evalLine(x,y,dirs[d][0],dirs[d][1],playerColor);}var c=Math.floor(CONFIG.BOARD_SIZE/2);score+=(CONFIG.BOARD_SIZE*2-Math.abs(x-c)-Math.abs(y-c))*0.3;return score;}
function evalLine(x,y,dx,dy,player){var count=0,empty=0,blocked=0;for(var i=1;i<=4;i++){var nx=x+dx*i,ny=y+dy*i;if(nx<0||nx>=CONFIG.BOARD_SIZE||ny<0||ny>=CONFIG.BOARD_SIZE){blocked++;break;}if(board[ny][nx]===player)count++;else if(board[ny][nx]===0){empty++;break;}else{blocked++;break;}}for(var i=1;i<=4;i++){var nx=x-dx*i,ny=y-dy*i;if(nx<0||nx>=CONFIG.BOARD_SIZE||ny<0||ny>=CONFIG.BOARD_SIZE){blocked++;break;}if(board[ny][nx]===player)count++;else if(board[ny][nx]===0){empty++;break;}else{blocked++;break;}}if(blocked===2)return 0;if(count>=5)return 1000000;if(count===4)return empty===2?100000:10000;if(count===3)return empty===2?5000:500;if(count===2)return empty===2?200:50;if(count===1&&empty===2)return 10;return 0;}
function gameLoop(){ctx.clearRect(0,0,W,H);if(gameState==='menu'){if(currentScreen==='main_menu')drawMenu();else if(currentScreen==='settings')drawSettings();else if(currentScreen==='create_game')drawCreateGame();}else if(gameState==='game'){drawGame();}requestAnimationFrame(gameLoop);}
function drawTopBar(){ctx.fillStyle='rgba(26,26,46,0.95)';ctx.fillRect(0,0,W,LAYOUT.topH);ctx.fillStyle='#fff';ctx.font=(W*0.035)+'px Arial';ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillText(currentTime,W-12,LAYOUT.topH/2);}
function drawMenu(){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#1a1a2e');g.addColorStop(1,'#16213e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawTopBar();ctx.fillStyle='#e94560';ctx.font='bold '+(W*0.1)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('技能五子棋',W/2,H*0.15);ctx.fillStyle='#9a8c98';ctx.font=(W*0.03)+'px Arial';ctx.fillText('Gomoku Game',W/2,H*0.21);for(var i=0;i<menuButtons.length;i++){var isHov=hoveredBtn&&hoveredBtn.id===menuButtons[i].id;drawDarkBtn(menuButtons[i],isHov);}}
function drawSettings(){ctx.fillStyle='#f5f5f5';ctx.fillRect(0,0,W,H);drawTopBar();ctx.fillStyle='#333';ctx.font='bold '+(W*0.06)+'px Arial';ctx.textAlign='center';ctx.fillText('设置',W/2,LAYOUT.topH+30);for(var i=0;i<menuButtons.length;i++){var b=menuButtons[i];var isHov=hoveredBtn&&hoveredBtn.id===b.id;if(b.type==='label'){ctx.fillStyle='#666';ctx.font=(W*0.04)+'px Arial';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}else if(b.type==='toggle')drawToggleBtn(b,isHov);else if(b.type==='btn')drawSmallBtn(b,isHov);}}
function drawCreateGame(){ctx.fillStyle='#f5f5f5';ctx.fillRect(0,0,W,H);drawTopBar();ctx.fillStyle='#333';ctx.font='bold '+(W*0.06)+'px Arial';ctx.textAlign='center';ctx.fillText('创建对局',W/2,LAYOUT.topH+30);for(var i=0;i<menuButtons.length;i++){var b=menuButtons[i];var isHov=hoveredBtn&&hoveredBtn.id===b.id;if(b.type==='label'){ctx.fillStyle='#666';ctx.font=(W*0.04)+'px Arial';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}else if(b.type==='diff')drawOptionBtn(b,settings.normalMode.difficulty===b.diff,isHov);else if(b.type==='color')drawOptionBtn(b,settings.normalMode.playerColor===b.color,isHov);else if(b.type==='toggle')drawToggleBtn(b,isHov);else if(b.type==='btn')drawSmallBtn(b,isHov);else if(b.type==='btn_large')drawLargeBtn(b,isHov);}}
function drawOptionBtn(b,isActive,isHov){ctx.fillStyle=isActive?'#e94560':isHov?'#f0f0f0':'#fff';roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,8);ctx.fill();ctx.strokeStyle=isActive?'#e94560':isHov?'#e94560':'#ddd';ctx.lineWidth=isHov?2.5:1.5;roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,8);ctx.stroke();ctx.fillStyle=isActive?'#fff':isHov?'#e94560':'#666';ctx.font=(W*0.035)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}
function drawDarkBtn(b,isHov){var bg=ctx.createLinearGradient(b.x-b.w/2,0,b.x+b.w/2,0);bg.addColorStop(0,isHov?'#4a4e69':'#3a3e59');bg.addColorStop(1,isHov?'#2d2d4a':'#22223b');ctx.fillStyle=bg;roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,12);ctx.fill();ctx.strokeStyle=isHov?'#e94560':'#4a4e69';ctx.lineWidth=isHov?3:2;roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,12);ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold '+(W*0.04)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}
function drawSmallBtn(b,isHov){ctx.fillStyle=isHov?'#555':'#666';roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,8);ctx.fill();ctx.fillStyle='#fff';ctx.font=(W*0.04)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}
function drawLargeBtn(b,isHov){ctx.fillStyle=isHov?'#d63850':'#e94560';roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,12);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold '+(W*0.045)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}
function drawToggleBtn(b,isHov){ctx.fillStyle=b.isOn?'#e94560':isHov?'#f5f5f5':'#fff';roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,8);ctx.fill();ctx.strokeStyle=b.isOn?'#e94560':isHov?'#e94560':'#ddd';ctx.lineWidth=isHov?2.5:1.5;roundRect(ctx,b.x-b.w/2,b.y-b.h/2,b.w,b.h,8);ctx.stroke();ctx.fillStyle=b.isOn?'#fff':isHov?'#e94560':'#666';ctx.font=(W*0.035)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.text,b.x,b.y);}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function drawGame(){ctx.fillStyle='#E5D4B3';ctx.fillRect(0,0,W,H);drawTopBar();drawPlayerInfo();drawBoard();drawPieces();drawActionArea();drawChatArea();if(gameOver)drawGameOver();}
function drawPlayerInfo(){var topH=LAYOUT.topH,infoY=topH+25;var leftX=W*0.15,rightX=W*0.85;ctx.fillStyle='#333';ctx.beginPath();ctx.arc(leftX,infoY,12,0,Math.PI*2);ctx.fill();ctx.fillStyle=currentPlayer===1?'#ffd700':'#888';ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('黑',leftX,infoY);ctx.fillStyle='#fff';ctx.strokeStyle='#999';ctx.lineWidth=1;ctx.beginPath();ctx.arc(rightX,infoY,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=currentPlayer===2?'#ffd700':'#888';ctx.fillText('白',rightX,infoY);if(settings.normalMode.countdown){ctx.font='bold 11px Arial';ctx.fillStyle=playerTime<=5?'#e94560':'#555';ctx.fillText(playerTime+'s',leftX,infoY+20);ctx.fillStyle=aiTime<=5?'#e94560':'#555';ctx.fillText(aiTime+'s',rightX,infoY+20);ctx.fillStyle='#e94560';ctx.font=(W*0.022)+'px Arial';ctx.fillText('停'+playerTimeoutCount+'次',leftX,infoY+34);}ctx.fillStyle='#555';ctx.font=(W*0.032)+'px Arial';ctx.textAlign='center';var tip=isMyTurn?'轮到你落子':'人机思考中...';ctx.fillText(tip,W/2,infoY);}
function drawBoard(){var bL=LAYOUT.boardLeft,bT=LAYOUT.boardTop;var lineLen=CONFIG.CELL_SIZE*(CONFIG.BOARD_SIZE-1);var cs=CONFIG.CELL_SIZE;ctx.fillStyle='#DEB887';ctx.fillRect(bL-6,bT-6,lineLen+12,lineLen+12);ctx.strokeStyle='#8B4513';ctx.lineWidth=1;for(var i=0;i<CONFIG.BOARD_SIZE;i++){var p=i*cs;ctx.beginPath();ctx.moveTo(bL,bT+p);ctx.lineTo(bL+lineLen,bT+p);ctx.stroke();ctx.beginPath();ctx.moveTo(bL+p,bT);ctx.lineTo(bL+p,bT+lineLen);ctx.stroke();}var stars=[[3,3],[3,9],[3,15],[9,3],[9,9],[9,15],[15,3],[15,9],[15,15]];ctx.fillStyle='#8B4513';for(var i=0;i<stars.length;i++){ctx.beginPath();ctx.arc(bL+stars[i][0]*cs,bT+stars[i][1]*cs,cs*0.15,0,Math.PI*2);ctx.fill();}}
function drawPieces(){var bL=LAYOUT.boardLeft,bT=LAYOUT.boardTop;var cs=CONFIG.CELL_SIZE,r=CONFIG.PIECE_RADIUS;for(var py=0;py<CONFIG.BOARD_SIZE;py++){for(var px=0;px<CONFIG.BOARD_SIZE;px++){var px2=bL+px*cs,py2=bT+py*cs;if(board[py][px]!==0){ctx.fillStyle='rgba(0,0,0,0.35)';ctx.beginPath();ctx.arc(px2+2,py2+2,r,0,Math.PI*2);ctx.fill();var grad=ctx.createRadialGradient(px2-3,py2-3,0,px2,py2,r);if(board[py][px]===1){grad.addColorStop(0,'#000');grad.addColorStop(1,'#1a1a1a');}else{grad.addColorStop(0,'#fff');grad.addColorStop(1,'#ccc');}ctx.fillStyle=grad;ctx.beginPath();ctx.arc(px2,py2,r,0,Math.PI*2);ctx.fill();if(board[py][px]===2){ctx.strokeStyle='#888';ctx.lineWidth=1;ctx.stroke();}if(lastMove&&lastMove.x===px&&lastMove.y===py){ctx.strokeStyle='#e94560';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px2,py2,r*0.4,0,Math.PI*2);ctx.stroke();}}else if(previewX===px&&previewY===py){var myColor=settings.normalMode.playerColor;ctx.strokeStyle=myColor===1?'rgba(0,0,0,0.6)':'rgba(120,120,120,0.9)';ctx.lineWidth=2.5;ctx.setLineDash([4,4]);ctx.beginPath();ctx.arc(px2,py2,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}}}
function drawActionArea(){var chatY=H-LAYOUT.chatH;var actionY=chatY-LAYOUT.actionH;var cx=W/2;ctx.fillStyle='#eee';ctx.fillRect(0,actionY,W,LAYOUT.actionH);ctx.strokeStyle='#ccc';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,actionY);ctx.lineTo(W,actionY);ctx.stroke();var btnW=160,btnH=50,btnX=cx-btnW/2,btnY=actionY+10;var isHov=hoveredBtn&&hoveredBtn.id==='confirm';ctx.fillStyle=canPlace?(isHov?'#d63850':'#e94560'):'#ccc';roundRect(ctx,btnX,btnY,btnW,btnH,10);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold '+(W*0.042)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('确认落子',cx,btnY+btnH/2);var abW=80,abH=36,abGap=12;var totalW=abW*3+abGap*2;var abStartX=cx-totalW/2;var abY=actionY+60;var labels=['认输','悔棋','求和'];var btnIds=['resign','undo','draw'];for(var i=0;i<3;i++){var bx=abStartX+i*(abW+abGap);var isH=hoveredBtn&&hoveredBtn.id===btnIds[i];ctx.fillStyle=isH?'#555':'#777';roundRect(ctx,bx,abY,abW,abH,6);ctx.fill();ctx.fillStyle=isH?'#fff':'#ddd';ctx.font=(W*0.032)+'px Arial';ctx.fillText(labels[i],bx+abW/2,abY+abH/2);}}
function drawChatArea(){var chatY=H-LAYOUT.chatH;ctx.fillStyle='#fff';ctx.fillRect(0,chatY,W,LAYOUT.chatH);ctx.strokeStyle='#e0e0e0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,chatY);ctx.lineTo(W,chatY);ctx.stroke();ctx.fillStyle='#aaa';ctx.font=(W*0.028)+'px Arial';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText('聊天',12,chatY+16);var msgY=chatY+32;for(var i=Math.max(0,chatMessages.length-2);i<chatMessages.length;i++){ctx.fillStyle='#333';ctx.font=(W*0.028)+'px Arial';ctx.fillText(chatMessages[i],12,msgY);msgY+=22;}ctx.fillStyle='#f5f5f5';roundRect(ctx,10,chatY+60,W-20,25,6);ctx.fill();ctx.strokeStyle='#e0e0e0';ctx.lineWidth=1;roundRect(ctx,10,chatY+60,W-20,25,6);ctx.stroke();ctx.fillStyle='#bbb';ctx.font=(W*0.03)+'px Arial';ctx.fillText('输入消息...',18,chatY+73);}
function drawGameOver(){ctx.fillStyle='rgba(0,0,0,0.6)';ctx.fillRect(0,0,W,H);var myColor=settings.normalMode.playerColor;var msg=winner===myColor?'你赢了!':'你输了!';var color=winner===myColor?'#ffd700':'#e94560';ctx.fillStyle=color;ctx.font='bold '+(W*0.14)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(msg,W/2,H*0.38);var btnW=150,btnH=48,btnY=H*0.52;ctx.fillStyle='#e94560';roundRect(ctx,W/2-btnW/2,btnY,btnW,btnH,10);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold '+(W*0.04)+'px Arial';ctx.fillText('再来一局',W/2,btnY+btnH/2);ctx.fillStyle='#888';roundRect(ctx,W/2-55,btnY+58,110,40,8);ctx.fill();ctx.fillStyle='#fff';ctx.font=(W*0.035)+'px Arial';ctx.fillText('返回菜单',W/2,btnY+78);}
init();
